# scala_library(
#     name = "repository",
#     srcs = glob(["*.scala"]),
#     visibility = ["//visibility:public"],
#     deps = ["//:common", "@third_party//3rdparty/jvm/com/typesafe/play:play_2_11", "@third_party//3rdparty/jvm/com/typesafe/play:play_json_2_11", "@third_party//3rdparty/jvm/org/reactivemongo:play2_reactivemongo_2_12"]
# )