scala_library(
    name = "formatter",
    srcs = glob(["formatter/*.scala"]),
    visibility = ["//visibility:public"],
    deps = ["@third_party//3rdparty/jvm/com/typesafe/play:play_json_2_11", 
    "@third_party//3rdparty/jvm/org/reactivemongo:play2_reactivemongo_2_12"]
)